### ISSUE TITLE
Stack overflow at compile time

### ISSUE THREAD

**Issue by dixonary** [elnabo/json2object#69]
Hello,

Firstly thanks for creating this library. Haxe's built in json parsing is a little lacking and this looks like a great addition to the ecosystem! However I seem to be running into an issue.

As far as I can tell, I'm using the library as intended:

(the omitted `LM...Raw` types are similar typedefs to this, and they are not mutually recursive or anything silly)

```haxe
typedef LMFrameDataRaw =
{
	currentFrameRate:Float,
	devices:Any,
	gestures:Array<LMGestureDataRaw>,
	hands:Array<LMHandDataRaw>,
	timestamp:Int,
	s:Int,
	t:Array<Float>,
	id:Int,
	interactionBox:
	{
		center:Array<Float>, size:Array<Float>
	},
	pointables:Array<LMPointableDataRaw>,
}

[...]	

var rawFrameParser = new json2object.JsonParser<LMFrameDataRaw>();
rawFrameParser.fromJson(text);
var frame:LMFrameDataRaw = rawFrameParser.value;
Sys.println(frame);
```

However, this provokes the following error:

```
/haxelib/json2object/3,8,0/src/json2object/reader/DataBuilder.hx:393: characters 57-62 : Uncaught exception Stack overflow
/usr/share/haxe/std/haxe/macro/Context.hx:1: character 1 : Called from here
/usr/share/haxe/std/haxe/macro/Context.hx:126: characters 10-32 : Called from here
/haxelib/json2object/3,8,0/src/json2object/utils/TypeTools.hx:136: characters 26-46 : Called from here
/haxelib/json2object/3,8,0/src/json2object/utils/TypeTools.hx:60: characters 15-25 : Called from here
/haxelib/json2object/3,8,0/src/json2object/utils/TypeTools.hx:64: characters 10-18 : Called from here

[...many copies of the line above...]

/haxelib/json2object/3,8,0/src/json2object/utils/TypeTools.hx:64: characters 10-18 : Called from here
/haxelib/json2object/3,8,0/src/json2object/reader/DataBuilder.hx:784: characters 80-97 : Called from here
/haxelib/json2object/3,8,0/src/json2object/reader/DataBuilder.hx:1024: characters 7-75 : Called from here
/haxelib/json2object/3,8,0/src/json2object/reader/DataBuilder.hx:1058: characters 12-37 : Called from here
/haxelib/json2object/3,8,0/src/json2object/reader/DataBuilder.hx:393: characters 57-62 : Called from here
```

Any thoughts what may be causing this?

**Comment by elnabo** [comment]
There was indeed a infinite loop, which should be fixed now. Hopefully this was your problem. 

Could you confirm if the last commit fixes your problem ?

**Comment by dixonary** [comment]
Thanks for the quick response!

It looks like it's partially solved - The infinite loop is no longer present.
However, it's throwing up a different error. The text of the error is as follows:

```
Type not found : T
/haxelib/json2object/git/src/json2object/reader/DataBuilder.hx:930: lines 930-953 : Defined in this class
```

Should I open another issue?

**Comment by elnabo** [comment]
Do you have one `final` field in the `typedef` affected by the parser ?

**Comment by dixonary** [comment]
No `final` fields in any typedefs. All fields are simple Array<Float> or Int or other typedefs containing the same types of fields.

**Comment by elnabo** [comment]
Could you share a complete sample so we could reproduce the problem ?

**Comment by dixonary** [comment]
Here's a gist to the complete type:

https://gist.github.com/dixonary/2834bb1ed2544b161f5b39994e682768

and the code to run it which was failing at compile time with the error above:

```
var rawFrameParser = new json2object.JsonParser<LMFrameData>();
rawFrameParser.fromJson(text);
var frame:LMFrameData = rawFrameParser.value;
Sys.println(frame);
```

**Comment by elnabo** [comment]
The last commit should have fixed your problem. The `Any` type, like `Dynamic`, isn't supported outside of custom parser. 

A proper message now reflect it.

If you want to keep the `Any` type you'll need a `@:jcustomparse` meta.

**Comment by dixonary** [comment]
Ah OK, thank you! I appreciate the time taken and your swift responses. Best of luck in the future!
